"""Criação da tabela AnbimaDebentures

Revision ID: 5b6f2b464613
Revises: 7ec49e856b9a
Create Date: 2024-11-21 20:35:38.359621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6f2b464613'
down_revision: Union[str, None] = '7ec49e856b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anbima_debentures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_ativo', sa.String(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('desvio_padrao', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('percent_pu_par', sa.Float(), nullable=True),
    sa.Column('percent_reune', sa.String(), nullable=True),
    sa.Column('percentual_taxa', sa.String(), nullable=True),
    sa.Column('pu', sa.Float(), nullable=True),
    sa.Column('taxa_compra', sa.Float(), nullable=True),
    sa.Column('taxa_indicativa', sa.Float(), nullable=True),
    sa.Column('taxa_venda', sa.Float(), nullable=True),
    sa.Column('val_max_intervalo', sa.Float(), nullable=True),
    sa.Column('val_min_intervalo', sa.Float(), nullable=True),
    sa.Column('emissor', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_contas_account_number', table_name='contas')
    op.drop_table('contas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type_fund', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('account_number', name='contas_pkey')
    )
    op.create_index('ix_contas_account_number', 'contas', ['account_number'], unique=False)
    op.drop_table('anbima_debentures')
    # ### end Alembic commands ###
